location       = "North Europe"
rg_name        = "dev-rg"
vnet_name      = "dev-vnet"
subnet_name    = "dev-subnet"
address_space  = ["10.0.0.0/16"]
subnet_prefix  = ["10.0.1.0/24"]
nsg_name       = "dev-nsg"
nic_name       = "dev-nic"
vm_name        = "dev-vm"
vm_size        = "Standard_B2s"
admin_user     = "azureuser"
admin_password = "DevPassword123!"
